### ISSUE TITLE
OAUTH Invalid Signature when pulling price info

### ISSUE THREAD

**Issue by imperfectal** [robbietjuh/py-bricklink#5]
I'm in a similar situation to debe13 as listed in issue #2 - New to Python and the BL api. 

I've taken the examples shown in the previous issue, and am trying to obtain price data. The problem I have is that I have expanded the example to have three lines/calls to the api, the results of which will be displayed/saved and otherwise manipulated later:

> inventory = api.inventory.getInventories()
> itemdets = api.catalog.getItem(item_type='SET', item_no='colsim-2')
> prices = api.catalog.getPriceGuide(item_type='SET', item_no='colsim-2')

The first two calls work fine, but the getPriceGuide  call fails with an error:

> Traceback (most recent call last):
>  File "C:\Users\alan\Dropbox\Python\BL\getapi.py", line 19, in <module>
>     prices = api.catalog.getPriceGuide(item_type='SET', item_no='colsim-2')
> File "C:\Users\alan\Dropbox\Python\BL\bricklink\methods.py", line 189, in getPriceGuide
>     return self.client.get(self.URL_CATALOG_PRICE_GUIDE.format(type=item_type, no=item_no), params)
>  File "C:\Users\alan\Dropbox\Python\BL\bricklink\api.py", line 64, in get
>     return self.request('GET', url, params)
> File "C:\Users\alan\Dropbox\Python\BL\bricklink\api.py", line 61, in request
>     return self.processResponse(response, method, url, params)
> File "C:\Users\alan\Dropbox\Python\BL\bricklink\api.py", line 43, in processResponse
>     elif meta['message'] == 'BAD_OAUTH_REQUEST': raise BricklinkBadOauthRequestException(meta['description'])
> BricklinkBadOauthRequestException: SIGNATURE_INVALID: Invalid Signature

I'm not quite sure why this is happening - I'm using the same parameters for each call! Any advice or guidance would be much appreciated by this newbie!

**Comment by robbietjuh** [comment]
Thanks for your interest in this project.

BrickLink is a bit obscure in their error descriptions. `SIGNATURE_INVALID` means that you either have an invalid signature or that the request you put in is invalid. In this case, it's obviously an invalid request since you can successfully call other API endpoints.

Your call to the Price Guide API seems to be invalid because BrickLink needs a bit more information in order to actually give you the prices for your set. BrickLink's [own documentation](http://apidev.bricklink.com/redmine/projects/bricklink-api/wiki/CatalogMethod#Get-Price-Guide) does not state that you need to actually specify anything other than the item_type and item_no parameters, but their documentation has not been updated ever since they actually announced the API and is therefor outdated at the moment, unfortunately. The documentation is still handy for looking up the description of parameters though.

So, to correct the official documentation on this: you will need to at least specify the item_type, item_no, guide_type and new_or_used parameters as per my knowledge. If you specify these, the request will actually go through successfully.

Below you will find a working example on how to call the Price Guide API:
`api.catalog.getPriceGuide(item_type='SET', item_no='colsim-2', guide_type='sold', new_or_used='N')`

I hope this solves your issue :-) Let me know if you need any more help.

**Comment by imperfectal** [comment]
Thanks for that. I'll have to revisit this next week, as the relevant files are on my office PC I'm sure it will work, but if it doesn't I'll just keep adding items until I get to the point where it does!

**Comment by robbietjuh** [comment]
Nice! I'll close this issue for now. You know where to find us if you need any more help :p
